### ISSUE TITLE
a pypi wheel ?

### ISSUE THREAD

**Issue by stonebig** [ioam/parambokeh#47]

**Comment by jbednar** [comment]
We are already planning to make it available via PyPi, but presumably it won't need a wheel since it's just Python code.  But I suppose they are now recommended even for pure Python?

**Comment by ceball** [comment]
If you don't provide a wheel, for most people pip will end up building a wheel locally anyway, and then installing it.

In any case, wheels are faster to install and involve far less code execution than sdist (no running complex setup.py files at install time...).

It's a bit like you're distributing a recipe for conda and getting users to build and install the package themselves, rather than distributing an actual conda package ;)

(It would be a universal wheel for hv, something like `python setup.py bdist_wheel --universal` to generate. I'm gradually providing wheels for all pyviz projects and would do the same for hv...if you can wait.)

**Comment by ceball** [comment]
Oops, I somehow thought this was on the hv tracker. There'll definitely be a universal wheel for parambokeh soon (I'll be doing it).

**Comment by stonebig** [comment]
about wheel, I fell over a pypa discussion telling it's the only thing they want to support for advanced version control issues (.... a bit like conda), and whishing the end of setup.py.... I didn't keep track of the link, may be a discussion implying dstufft , pmoore or ncgohlan.

**Comment by stonebig** [comment]
any progress ?

**Comment by ceball** [comment]
The next release will include a wheel on pypi. I don't think we'll produce a wheel for any existing release unless there's some special reason a wheel is needed immediately.

Although I can't say when the next release will be, it should be soon...

**Comment by philippjfr** [comment]
Definitely quite soon, already a bunch of features that need a release, e.g. JLab support and label formatters.

**Comment by ceball** [comment]
There are wheels now from 0.2.3 onward. Please let us know if you have any problems with them.

**Comment by stonebig** [comment]
thanks !
