### ISSUE TITLE
Best practice for getting boolean value

### ISSUE THREAD

**Issue by kcpevey** [ioam/parambokeh#73]
I have a `param.Parameterized` class with a bunch of Booleans. If the `parambokeh.Widge`t has it toggled as `True`, I want to collect that value and process it. My problem is that what I get back from param is a `param.Boolean object`. In many other cases, python just understands it, but when I check that value against `True` its not understood. My current workaround is to use `val.__get__(None,None)` but surely there is a better approach?  
  
Test snippet:  
```
import param

class BaseClass(param.Parameterized):
    boolean1                 = param.Boolean(True, doc="A sample Boolean parameter")
    boolean2                 = param.Boolean(False, doc="A sample Boolean parameter")
    
    def widget_to_list(self):
        for name, val in self.params().items():
            if val.__get__(None,None) is True:
                print(val.__get__(None,None))
base = BaseClass()
base.widget_to_list()
```

**Comment by kcpevey** [comment]
Actually, that will always return the default value... how can I get it to return a dynamic value based on the visualized widget?

**Comment by jbednar** [comment]
Hmm.  The code above doesn't contain any widgets, as it's only importing from Param and not ParamBokeh, and not calling parambokeh.widgets.  `self.params()` returns a dictionary of Parameter objects, not widgets, so a better name for `widget_to_list` as written is `parameters_to_list`.  Parameter objects, as you note, only store default values; the actual values are stored as attributes on the objects.

You can use attribute access to get the value for the parameter, e.g. as BaseClass.boolean1 to get the value at the class level (which is the same as the default), or base.boolean1 to get the value from the instance `base`. Which one will have the current value controlled by any widget depends on whether you used parambokeh.Widgets on the class (`Widgets(BaseClass)`) or on the instance (`Widgets(base)`).

If what you want is to be able to iterate over the current parameter values without knowing the parameter names, you can use `getattr()`:

```
import param

class BaseClass(param.Parameterized):
    boolean1                 = param.Boolean(True, doc="A sample Boolean parameter")
    boolean2                 = param.Boolean(False, doc="A sample Boolean parameter")
    
    def widget_to_list(self):
        for name, val in self.params().items():
            if getattr(self,name) is True:
                print(name,":", getattr(self,name))
base = BaseClass()
base.widget_to_list()
```

**Comment by kcpevey** [comment]
`getattr()` is definitely one of the things I was looking for. Thanks.  
  
>Which one will have the current value controlled by any widget depends on whether you used parambokeh.Widgets on the class (Widgets(BaseClass)) or on the instance (Widgets(base)).  
  
It seems the `__get__` function reverts to the class default values instead of the instance values. That was confusing me, but I got it now.   
  
I went with `widget_to_list` because in the actual code, I DO visualize with `parambokeh.Widgets(base)`. I find it a little odd on the verbage since you're right, I'm querying the the instance of BaseClass, but I'm gathering values that may have been change via widget. The widget isn't *required* but if it used, it will affect the result.

**Comment by jbednar** [comment]
> It seems the `__get__` function reverts to the class default values instead of the instance values. That was confusing me, but I got it now.

That's confusing, yes.  It has to do with what bits are implemented on Parameter objects, and what bits are done by a Parameterized.  For `val.__get__()`, `val` is an object of type Parameter. A Parameter captures metadata that determines how that object acts, but a given parameter 'x' has only a single Parameter object across all instances of a Parameterized class, and thus can only store the default value, not the value per Parameterized instance.  In the code above, I'm getting the name of the parameter from the Parameter object, but there's no way to get the value from there; instead the value is being requested from the Parameterized instance.  Only the Parameterized instance (here "base") has a copy of the current parameter value, hence using `getattr` on that instance to fetch the value.

I'd strongly recommend being careful with method names and attribute names, because Param is very specifically designed to let you capture all the aspects of your system that have nothing to do with widgets (i.e., parameter values regardless of whether they were set in a config file, from the command line, using a widget, and so on), keeping those aspects entirely separate from any widgets you may or may not use with them.  That's really important when your code can be used in different contexts at different times, such as in a batch run, in a notebook, in a deployed dashboard, in a report, with some future yet-to-be-invented GUI, etc.

**Comment by kcpevey** [comment]
>I'd strongly recommend being careful with method names and attribute names, because Param is very specifically designed to let you capture all the aspects of your system that have nothing to do with widgets   
  
Good advice. I appreciate the tips!
